name: JumbleHill
version: 1.1
main: me.zachbears27.JumbleHill
description: Jumble Hill Plugin
author: A_Brave_Panda
softdepend: [ActionBarAPI]
commands:
    jumblehill:
        usage: /<command>
        aliases: [jh]
        description: The Jumblest Of Commands!
      